version: '3'
services:
  web:
    #    build: .
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000" # Map port 80 FROM the .travis EXPOSE PORT to 3000
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]